### ISSUE TITLE
Android Dev Env Updates

### ISSUE THREAD

**Issue by newtewt** [medic/cht-android#117]
Update Gradle and update the project to work with new changes or we can continue using the old one and add an updated README note to caution against any potential new updates that might cause errors. 

Add the `x86` and `x86_64` builds so you can use emulators. 

Get rid of make and updated README to show how to use gradle to build. Removes an extra dependency that not all OS have and gets people into using gradle!

**Comment by mrsarm** [comment]
Going to close this ticket that duplicates #174 that I'm working on.

> Update Gradle and update the project to work with new changes or we can continue using the old one and add an updated README note to caution against any potential new updates that might cause errors.

Upgrading to latest version now...

> Add the x86 and x86_64 builds so you can use emulators.

I added in the past the configuration in the build settings but commented, we cannot enable it by default because it will double the time CI takes to build, and generate a lot of useless APKs.

> Get rid of make and updated README to show how to use gradle to build. Removes an extra dependency that not all OS have and gets people into using gradle!

We added small additions in the past months, going to add a few more, like a note about how to enable x86* builds for local development.
