### ISSUE TITLE
Upgrade target sdk to 30 and associated changes

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#164]
Update `targetSdkVersion` to 30 along with a range of other requirements, [documented here](https://developer.android.com/distribute/best-practices/develop/target-sdk).

New apps will require this by August 2021
App updates will require this by November 2021

**Comment by garethbowen** [comment]
With the change to the app bundle format we'll need to make sure the app can still be sideloaded, and ideally still able to be distributed via F-Droid.

**Comment by mrsarm** [comment]
### Progress Update

- [x] The requirement for new and existing Apps to upgrade the targeted **SDK to version 30** (Android 11) was [implemented](https://github.com/medic/cht-android/pull/194) and merged into master this week.
- [x] **We already complaint with other new requirements for existing apps**, e.g. the minimal version of the algorithm to sign APKs and Bundles is v2, that is the version we use now.
- [x] The are other requirements that we have verified don't apply to our apps, e.g. location permission in the background has new requirements but we only access location in the foreground.
- [ ] New apps in the Play Store (not updates from existing apps) will require to be uploaded using the new Bundle format (.aab). We did some experiments with this format and creates this files is an easy task. The bundle cannot be used for side-loading, but we can still generate the .apk files for each flavor along with the .aab files. We will implement a specific task in the CI to produce the .aab files for new flavors.
- [ ] New apps in the Play Store (not updates from existing apps) after being uploaded with the new Bundle format will be converted by Google to optimized APKs in the Play Store, so Google need the same or a new created private key to sign the app. We are defining a new workflow for this.

#### Proposed workflow

In summary, the new  [workflow](https://docs.google.com/document/d/1ZAiY-67DHdX7AvFxZoXo_FLNwztG6zYdeN9PcwxFtmk/edit?usp=sharing) is:

- New apps from partners will have their own private keys to sign the app, not using the one that we currently use to sign existing apps.
- We will use the same set of keys to sign the bundle (Upload Key) and to let Google sign the APKs (Signing App Key), allowing us to keep generating .apk files for sideloading compatible with the .apk files generated by Google (signed with the same key).
- We will make changes in the CI pipelines to generate both .apk and .aab files, signed with this key, so each time a new private key is generated to sign an app, we need to setup it in our repo. We need to document well each step to create a new flavored version of the app. We also recommend to only setup one key for partner, using the new key for each new flavored app created by that partner.
- After the creation of the app in our repo and in the Play Console, the owner of the Play account (partner or us) will register the key for signing, and upload the .aab file for publishing the release.

**Comment by mrsarm** [comment]
Ready for AT, tag [v0.8.1-alpha.6](https://github.com/medic/cht-android/releases/tag/untagged-b923d2ca73daea2c7b60).

Although this is not done yet and there is no new features, we need to test that the SDK change and building changes don't affect the normal function of the App, and we can continue releasing apps after the end of the month when no apps can't be updated in the Play Store without targeting Android 11.

This alpha also include the changes from another PR (https://github.com/medic/cht-android/pull/192). In summary the list of changes are:

- Target SDK 30 (Android 11)
- Upgrade Java and building dependencies
- Refactor some methods to lambda (Java 8+)
- Skip upload of APKs for `webview-armeabi-v7a` arch not used
- Disable for now demo app publishing (demo.dev.medicmobile.org is unmaintained)
- `make assemble-all` only assemble release versions
- Refactor Make config
- Moved suppression of linters, setting the suppression in particular fragment of codes instead of the entire class
- Typo in Makefile argument: ~flavour~ → flavor

But again no change has an impact in the UI or the usability of the app.

**Comment by mrsarm** [comment]
Quality Assurance, by mistake I have merged a [PR](https://github.com/medic/cht-android/pull/195) into master that wasn't tested yet. Anyway, the PR does not introduce code changes, only assets changes (logo and brand name), so I have released a new alpha version that replace the one mentioned above for release testing. Sorry for the inconvenient.

New version is [v0.8.1-alpha.7](https://github.com/medic/cht-android/releases/tag/untagged-005c758a4242a7ff1d70).

Also I notice that this new release will also include another feature that was tested but not released yet: [Add version of android app](https://github.com/medic/cht-core/issues/6741).

So the final list of features in this release is:

- Target SDK 30 (Android 11)
- Upgrade Java and building dependencies
- Refactor some methods to lambda (Java 8+)
- Skip upload of APKs for `webview-armeabi-v7a` arch not used
- Disable for now demo app publishing (demo.dev.medicmobile.org is unmaintained)
- `make assemble-all` only assemble release versions
- Refactor Make config
- Moved suppression of linters, setting the suppression in particular fragment of codes instead of the entire class
- Typo in Makefile argument: ~flavour~ → flavor
- **New branding icon, and switching from "Medic Mobile" to "Medic"**
- **Add more info about the version of the Android app**

**Comment by ngaruko** [comment]
1. App rebranded as per https://github.com/medic/cht-core/issues/7128 

| Before  | Now |
| ------------- | ------------- |
| 
![image](https://user-images.githubusercontent.com/6979995/126720020-aa07e81d-17d4-40b6-8a40-511d33876b77.png)
 | ![image](https://user-images.githubusercontent.com/6979995/126719369-492ac2d3-d6aa-4227-b0a4-ec826f4732be.png) |

2.

**Comment by mrsarm** [comment]
@ngaruko we cannot change flavor's names or application's ids, because it would make the app to turn into a new app, e.g. the application Id is used by Google to identify the app in the Play Store, and it is an immutable identifier.

**Comment by ngaruko** [comment]
Also  @mrsarm, two more observations,  none seems to affect the functionality and not all are  related to this  PR - thus will be dealt in another issue, if needed. Just leaving it here for reference!

1.  there are a few errors (from code inspection)
![image](https://user-images.githubusercontent.com/6979995/126730646-61a11db9-4259-4a3a-be64-1bc735c5afa3.png)

2. If/when we rename [medic-api](https://github.com/medic/cht-core/blob/master/api/src/routing.js#L312) to cht-api , this will call for change in cht-android [AppUrlVerifier](https://github.com/medic/cht-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/AppUrlVerifier.java#L25)

**Comment by ngaruko** [comment]
Other than that, looks good to go, feel free to merge @mrsarm .

**Comment by mrsarm** [comment]
Closing this because we did merge a PR with the changes to be able to publish **updates of the existing apps**, while I have created https://github.com/medic/cht-android/issues/200 to keep track of the necessary changes to publish **new apps**.
