### ISSUE TITLE
Change developer address and company name in Google Play

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#171]
We need to change the developer address and company name in Google Play.

Company name: ~Medic Mobile, Inc~ **Medic, Inc** (is this correct?, do we need to preserve the `, Inc` at the end?).

Developer address: ~hello@medicmobile.org~ **hello@medic.org**

Visit website: ~http://medicmobile.org/~ **https://medic.org/**

The company address also looks outdated, now: _3254 19th Street, Floor Two San Francisco, CA 94110 USA_, but our contact page https://medic.org/contact/ points to a new address.

The changes also need to be addressed in the source code of the app, we should change "Medic Mobile" in the name with just "Medic".

Because we are changing the name of the company I guess this my lead to extra verifications from Google, so check whether it my require additional steps.

CC @michaelkohn

**Comment by mrsarm** [comment]
Now thinking again about the app name (not the company name) to just "Medic", would that be approved by Google? like, it is just one word and a very important one, so maybe is better to keep "Medic Mobile" for the name of the app?

**Comment by garethbowen** [comment]
@abbyad This seems to be a relatively simple change but I don't currently have permission to do it. Can you do it, and/or grant me the permission to update it in future?

**Comment by abbyad** [comment]
I've made some of the changes, and will discuss access separately.

# Company Name
The Company name is still `Medic Mobile, Inc` officially, at least for now, but we can likely use just `Medic` here. That name is taken though, so trying `Medic.`, and waiting for approval.

# Dev Page
Here is the [newly updated dev page](https://play.google.com/store/apps/dev?id=7987044497930745454), and mailing address has been updated (not seen):
![image](https://user-images.githubusercontent.com/789512/113907936-f4f39680-97a3-11eb-9630-3b702f736efe.png)

# App Branding
We should update the branding and email for each of our 25 product apps, and this needs to be done for each app individually. The requirements for images and icons has changed since many of these were created, so they may need to be updated as well:

![image](https://user-images.githubusercontent.com/789512/113908310-62072c00-97a4-11eb-8b68-5a93bd9fe1dd.png)

![image](https://user-images.githubusercontent.com/789512/113908668-cc1fd100-97a4-11eb-8faf-5528ad5652db.png)



@mrsarm if the changes above are ok can you close the issue, and I'll follow up with teammates separately to update the individual apps.

**Comment by mrsarm** [comment]
Closing this because in https://github.com/medic/cht-android/pull/195 we made the last changes needed, and we still need to rename the reference apps in the Play Store, but there is another ticket to keep track of that (https://github.com/medic/cht-android/issues/172).
