### ISSUE TITLE
Update name and branding of Medic Mobile apps in Play Store

### ISSUE THREAD

**Issue by abbyad** [medic/cht-android#172]
As seen in https://github.com/medic/medic-android/issues/171#issuecomment-815101972, the apps in the Google Play store need to be updated to match updated names and branding. This is a placeholder issue for now.

**Comment by mrsarm** [comment]
Assigning the ticket myself, we did the changes in the repo (~Medic Mobile~ → Medic) and the same in the Google account. Only rest to do the same in the apps' names. I'll try to rename the apps when publishing the v0.9.0 release (reference apps).

**Comment by mrsarm** [comment]
I was going to change the name of the app in one the demo apps: **Medic Mobile (gamma)**, and like we did in the last [PR](https://github.com/medic/cht-android/pull/195) replacing _"Medic Mobile"_ by just _"Medic"_:

![Play Store - Medic gamma](https://user-images.githubusercontent.com/1608415/128241250-edb9b017-3c2f-4d29-9e50-80dfca8fda27.png)

But then I got panic remembering that somebody mentioned about Google rejecting apps with short names with the word "Medic" since Covid started, but not sure.

Furthermore, we did rename the reference app "Medic Mobile" to "CHT Android" in the [code repo](https://github.com/medic/cht-android/blob/master/src/main/res/values/strings.xml#L3), and there is a discussion out there about whether to use "CHT Android" or just "CHT" as the app name (I don't remember where I saw that thread).

So, right now all the reference apps has the prefix "Medic Mobile", how we shoud replace that prefix?
- Medic
- CHT Android
- CHT
- _[Suggestions ...]_

The reference apps are (listed with the exact name in the Play Store):
- Medic Mobile
- Medic Mobile (gamma)
- Medic Mobile - Simprints

CC @garethbowen

**Comment by garethbowen** [comment]
I think "Medic" is ok on the Play Store, it's mostly "covid" that raised red flags. It's only a demo app so if we have to change it back then it's not a big deal.

Generally "CHT" should be used when it's something that's useful for anyone in the community, and "Medic" used when it's only used internally to Medic. So "CHT" for the unbranded app is sensible because it could be used to access any CHT project. In this case because all of those URLs are hardcoded to point to Medic testing servers I think the apps should be named "Medic".

So... I think the names should be:

- "Medic"
- "Medic - gamma"
- "Medic - Simprints"

**Comment by mrsarm** [comment]
I have renamed the reference apps to Medic ~Mobile~ ... in the Play Store , and all passed the Google review process.
