### ISSUE TITLE
Update gradle version and relevant dependencies 

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-android#174]
As we move on supporting later android sdks (29, 30), some features are becoming hard to support without updating the gradle and some dependencies.

**Comment by mrsarm** [comment]
Hey @ngaruko , could you detail what are the cases where the Gradle version is giving you errors or deprecation warnings?

I want also as you say determine whether we need a newer version of Gradle for the SDK upgrade (https://github.com/medic/medic-android/issues/164). At a first glance, we do need to upgrade in order to use the latest Android plugin, checkout https://developer.android.com/studio/releases/gradle-plugin#updating-gradle , but not sure if we need one of the latest versions of the plugins in order to upgrade the Android SDK.

Also worth to note:

- JCenter is one of the main repos used by Gradle and our project to get the dependencies, and it's going to shutdown in a few months, and the replacement for some of the dependencies is a repo for Google, at least for the Android dependencies, check https://developer.android.com/studio/releases/gradle-plugin#updating-plugin
- We are not supporting Java syntax newer than Java 7, which though is not a big problem but annoying not being able to use important changes introduced in Java 8, may be a problem in the future. Now we can use newer compilers and Gradle takes care of setting the right target version, but at some point that may not work well, specially because using higher versions of compiler to target older versions can lead to errors like using core API libraries that are not available in the older versions and not detected by the compiler.

**Comment by latin-panda** [comment]
++ 1

I'm also receiving the warning regarding JCenter and Gradle, also definitely would love some features of Java 8.

Mockito has a lib for Android with tools for testing static and final implementations which can help us getting coverage to places where we don't have control, but some of these tools need Java8+.

I think we might need to add [this](https://developer.android.com/studio/write/java8-support#library-desugaring) for Java 8:

``` java
android {
    defaultConfig {
        // Required when setting minSdkVersion to 20 or lower
        multiDexEnabled true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by ngaruko** [comment]
@mrsarm - I have put a little more details on the [medic-gateway issue](https://github.com/medic/medic-gateway/issues/178#issue-876928585). That could be a starting point, but basically I was trying to write a roboletric test targeting API 29+ and I came across the error. Then upon updating robolectric, I was prompted to update Gradle plugin. Then a few more dependencies started to fall apart, including some hosted on JCenter (like our static code analysis plugin `com.noveogroup.android.check`) , which as @latin-panda mentioned above is shutting down.
