### ISSUE TITLE
Default browser setting

### ISSUE THREAD

**Issue by makombe** [medic/cht-android#181]
Does medic android allow one to set his/her preferred default browser to be used by the app?
For instance, if I want to set the default browser for the app to be Firefox, where can it be effected?
@garethbowen @derickl @ngaruko  any heads up on this?

**Comment by garethbowen** [comment]
Currently there are two versions of the apk...

1. The Crosswalk apk uses the now deprecated Crosswalk library to bundle a specific version of Chromium. This is needed for Android 4.x phones because the included webview cannot be upgraded from an ancient version of Chromium. This is baked in and cannot be updated.
2. The Webview apk which uses the included Android System Webview. This is needed for Android 10+ phones because Crosswalk is incompatible. It is recommended to get your Webview app up to date to benefit from the latest browser improvements as well as ensure the CHT webapp works as expected. This is an Android system app which cannot be switched out.

Currently we use the Crosswalk version for Android 5-9, but with the release of cht-android v1.0.0 we plan to switch to using Webview for Android 5-12+ and dropping support for Android 4.x altogether.

A third option is to look at using the CHT as a PWA, that is, using a browser of your choice (eg: Firefox for Android) to access the URL directly with no Android app wrapper.

Why do you want to change the webview provider from the default?

**Comment by ojwanganto** [comment]
@garethbowen thanks for this feedback. We haven't been able to successfully configure the facility networks to support HTTPS and we defaulted to the use of firefox ( and the PWA route). No other browser works and we thought that invoking firefox from the app could be an easier way to bypass the HTTPS requirement for browser replication. 
Our users prefer to use the app as opposed to the browser every time they want to access CHT (Afyastat in our case)

**Comment by garethbowen** [comment]
At this time there is no way to change the browser used for a webview. There are other technologies like Crosswalk and Geckoview but they both require significant changes to the application and have some serious drawbacks that make them unlikely candidates for replacement.

For now I suggest sticking with the PWA approach until we get HTTPS sorted for your deployment.

**Comment by mrjones-plip** [comment]
@ojwanganto & @makombe - Is this the part of the issue as [described here](https://github.com/medic/cht-android/issues/186) and part of this larger [forum post](https://forum.communityhealthtoolkit.org/t/prototyping-a-fully-offline-cht-server-environment/1232/23)?  I'm ask so that we can ensure all the issues are linked together.
