### ISSUE TITLE
Re-enable storage permissions and remove unbranded-test flavour

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-android#257]
[This ticket](https://github.com/medic/cht-android/issues/148) in cht-android re-enable the storage permission that was [removed last year](https://github.com/medic/cht-android/commit/9e0d1e28765c4c94206fc03b8db396f6c99b01f5), with a new flavour `unbranded-test` created.
I would [suggest](https://github.com/medic/cht-android/issues/148#issuecomment-1088399233) we remove it to avoid confusion in the future.
Also, think of re-enabling the storage permission for partners who use app launcher.
![image](https://user-images.githubusercontent.com/6979995/161831461-55aa87a0-9b70-48da-971c-93c347e452e4.png)

**Comment by latin-panda** [comment]
Cross posting here for the record:
- `unbranded_test` is removed.
- Partners will need to add the permission by themselves, so they can control when to release it and when communicate the change to their CHWs. A partner might want to add a permission if they are using a feature that requires it. Because of that, we won't update any of the partners' flavor.
